/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Lenovo
 */
public class ArqueoCaja extends javax.swing.JPanel {

    /**
     * Creates new form ArqueoCaja
     */
    public ArqueoCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpanelEsquinasRedondas1 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas10 = new Estilos_panel.jpanelEsquinasRedondas();
        horaArqueoCaja1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jpanelEsquinasRedondas9 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        monedanacionalArqueoCaja = new javax.swing.JTextField();
        facturanoArqueoCaja = new javax.swing.JTextField();
        recibooficialArqueoCaja = new javax.swing.JTextField();
        facturadelsegundonoArqueoCaja = new javax.swing.JTextField();
        recibooficialdelsegundonoArqueoCaja = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jpanelEsquinasRedondas3 = new Estilos_panel.jpanelEsquinasRedondas();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpanelEsquinasRedondas6 = new Estilos_panel.jpanelEsquinasRedondas();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCordobas = new javax.swing.JTable();
        jpanelEsquinasRedondas5 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpanelEsquinasRedondas7 = new Estilos_panel.jpanelEsquinasRedondas();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDolares = new javax.swing.JTable();
        totalFacturaContado = new javax.swing.JTextField();
        totalUSFacturaContado1 = new javax.swing.JTextField();
        tcdehoyFacturaContado = new javax.swing.JTextField();
        sobranteArqueoCaja = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        converFacturaContado1 = new javax.swing.JTextField();
        montorecibidoArqueoCaja = new javax.swing.JTextField();
        jpanelEsquinasRedondas8 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jpanelEsquinasRedondas11 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas12 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        elaboradoArqueoCaja = new javax.swing.JTextField();
        CajeroArqueoCaja = new javax.swing.JTextField();

        jpanelEsquinasRedondas1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelEsquinasRedondas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelEsquinasRedondas10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horaArqueoCaja1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpanelEsquinasRedondas10.add(horaArqueoCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 250, 30));

        jPanel3.setBackground(new java.awt.Color(217, 217, 246));

        jpanelEsquinasRedondas9.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ARQUEO DE CAJA CHICA");

        javax.swing.GroupLayout jpanelEsquinasRedondas9Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas9);
        jpanelEsquinasRedondas9.setLayout(jpanelEsquinasRedondas9Layout);
        jpanelEsquinasRedondas9Layout.setHorizontalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelEsquinasRedondas9Layout.setVerticalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hora");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
            .addComponent(jpanelEsquinasRedondas9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpanelEsquinasRedondas9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)))
        );

        jpanelEsquinasRedondas10.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(217, 217, 246));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Datos");

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("No.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas10.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 638, 29));

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Moneda nacional (C$)");
        jpanelEsquinasRedondas10.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 30));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Facturas del No.");
        jpanelEsquinasRedondas10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 30));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Recibo oficial de caja");
        jpanelEsquinasRedondas10.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 30));

        monedanacionalArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        monedanacionalArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas10.add(monedanacionalArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 199, 30));

        facturanoArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        facturanoArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas10.add(facturanoArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 199, 30));

        recibooficialArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        recibooficialArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas10.add(recibooficialArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 199, 30));

        facturadelsegundonoArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        facturadelsegundonoArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas10.add(facturadelsegundonoArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 62, 30));

        recibooficialdelsegundonoArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        recibooficialdelsegundonoArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas10.add(recibooficialdelsegundonoArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 62, 30));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("al No.");
        jpanelEsquinasRedondas10.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, 30));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("al No.");
        jpanelEsquinasRedondas10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, 30));

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 640, 286));

        jpanelEsquinasRedondas3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 246));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cordobas");

        tablaCordobas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaCordobas);

        javax.swing.GroupLayout jpanelEsquinasRedondas6Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas6);
        jpanelEsquinasRedondas6.setLayout(jpanelEsquinasRedondas6Layout);
        jpanelEsquinasRedondas6Layout.setHorizontalGroup(
            jpanelEsquinasRedondas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jpanelEsquinasRedondas6Layout.setVerticalGroup(
            jpanelEsquinasRedondas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpanelEsquinasRedondas6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelEsquinasRedondas6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 320, -1));

        jpanelEsquinasRedondas5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DETALLE DEL EFECTIVO");

        javax.swing.GroupLayout jpanelEsquinasRedondas5Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas5);
        jpanelEsquinasRedondas5.setLayout(jpanelEsquinasRedondas5Layout);
        jpanelEsquinasRedondas5Layout.setHorizontalGroup(
            jpanelEsquinasRedondas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpanelEsquinasRedondas5Layout.setVerticalGroup(
            jpanelEsquinasRedondas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEsquinasRedondas5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jpanelEsquinasRedondas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel4.setBackground(new java.awt.Color(217, 217, 246));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dolares");

        tablaDolares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaDolares);

        javax.swing.GroupLayout jpanelEsquinasRedondas7Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas7);
        jpanelEsquinasRedondas7.setLayout(jpanelEsquinasRedondas7Layout);
        jpanelEsquinasRedondas7Layout.setHorizontalGroup(
            jpanelEsquinasRedondas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jpanelEsquinasRedondas7Layout.setVerticalGroup(
            jpanelEsquinasRedondas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpanelEsquinasRedondas7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelEsquinasRedondas7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, -1));

        totalFacturaContado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        totalFacturaContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFacturaContadoActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(totalFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, 30));

        totalUSFacturaContado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        totalUSFacturaContado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUSFacturaContado1ActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(totalUSFacturaContado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 100, 30));

        tcdehoyFacturaContado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tcdehoyFacturaContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcdehoyFacturaContadoActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(tcdehoyFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 100, 30));

        sobranteArqueoCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sobranteArqueoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobranteArqueoCajaActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(sobranteArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 200, 30));

        jPanel7.setBackground(new java.awt.Color(217, 217, 246));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total U$");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 310, -1));

        jPanel8.setBackground(new java.awt.Color(217, 217, 246));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TC de hoy");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 310, -1));

        jPanel9.setBackground(new java.awt.Color(217, 217, 246));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, -1));

        jPanel5.setBackground(new java.awt.Color(217, 217, 246));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Monto recibido (C$)");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sobrante");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpanelEsquinasRedondas3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 640, -1));

        jPanel10.setBackground(new java.awt.Color(217, 217, 246));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Conver-C$");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 310, -1));

        converFacturaContado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        converFacturaContado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converFacturaContado1ActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(converFacturaContado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 100, 30));

        montorecibidoArqueoCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        montorecibidoArqueoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montorecibidoArqueoCajaActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas3.add(montorecibidoArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 200, 30));

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, -1, 618));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Managua, Nicaragua");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel11.setText("Empresa Team 8");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Telefono No. 88888-76753");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setText("Foto");

        javax.swing.GroupLayout jpanelEsquinasRedondas8Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas8);
        jpanelEsquinasRedondas8.setLayout(jpanelEsquinasRedondas8Layout);
        jpanelEsquinasRedondas8Layout.setHorizontalGroup(
            jpanelEsquinasRedondas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas8Layout.createSequentialGroup()
                .addGroup(jpanelEsquinasRedondas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelEsquinasRedondas8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpanelEsquinasRedondas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelEsquinasRedondas8Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12)))
                    .addGroup(jpanelEsquinasRedondas8Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel13)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelEsquinasRedondas8Layout.setVerticalGroup(
            jpanelEsquinasRedondas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 6, -1, -1));

        guardar.setBackground(new java.awt.Color(204, 204, 255));
        guardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorder(null);
        guardar.setBorderPainted(false);
        guardar.setFocusPainted(false);
        guardar.setFocusable(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 196, 90, 30));

        jpanelEsquinasRedondas11.setBackground(new java.awt.Color(240, 240, 240));
        jpanelEsquinasRedondas11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelEsquinasRedondas12.setBackground(new java.awt.Color(189, 189, 250));
        jpanelEsquinasRedondas12.setPreferredSize(new java.awt.Dimension(1018, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos del vendedor");

        javax.swing.GroupLayout jpanelEsquinasRedondas12Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas12);
        jpanelEsquinasRedondas12.setLayout(jpanelEsquinasRedondas12Layout);
        jpanelEsquinasRedondas12Layout.setHorizontalGroup(
            jpanelEsquinasRedondas12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelEsquinasRedondas12Layout.setVerticalGroup(
            jpanelEsquinasRedondas12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpanelEsquinasRedondas11.add(jpanelEsquinasRedondas12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel11.setBackground(new java.awt.Color(217, 217, 246));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cajero (a)");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Elaborado por");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jpanelEsquinasRedondas11.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 640, -1));

        elaboradoArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        elaboradoArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas11.add(elaboradoArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 191, 30));

        CajeroArqueoCaja.setForeground(new java.awt.Color(204, 204, 204));
        CajeroArqueoCaja.setBorder(null);
        jpanelEsquinasRedondas11.add(CajeroArqueoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 191, 30));

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 928, -1, 145));

        jScrollPane1.setViewportView(jpanelEsquinasRedondas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void sobranteArqueoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobranteArqueoCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobranteArqueoCajaActionPerformed

    private void tcdehoyFacturaContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcdehoyFacturaContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcdehoyFacturaContadoActionPerformed

    private void totalUSFacturaContado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUSFacturaContado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUSFacturaContado1ActionPerformed

    private void totalFacturaContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFacturaContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFacturaContadoActionPerformed

    private void converFacturaContado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converFacturaContado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_converFacturaContado1ActionPerformed

    private void montorecibidoArqueoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montorecibidoArqueoCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montorecibidoArqueoCajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CajeroArqueoCaja;
    public javax.swing.JTextField converFacturaContado1;
    public javax.swing.JTextField elaboradoArqueoCaja;
    public javax.swing.JTextField facturadelsegundonoArqueoCaja;
    public javax.swing.JTextField facturanoArqueoCaja;
    public javax.swing.JButton guardar;
    public javax.swing.JTextField horaArqueoCaja1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas1;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas10;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas11;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas12;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas3;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas5;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas6;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas7;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas8;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas9;
    public javax.swing.JTextField monedanacionalArqueoCaja;
    public javax.swing.JTextField montorecibidoArqueoCaja;
    public javax.swing.JTextField recibooficialArqueoCaja;
    public javax.swing.JTextField recibooficialdelsegundonoArqueoCaja;
    public javax.swing.JTextField sobranteArqueoCaja;
    private javax.swing.JTable tablaCordobas;
    private javax.swing.JTable tablaDolares;
    public javax.swing.JTextField tcdehoyFacturaContado;
    public javax.swing.JTextField totalFacturaContado;
    public javax.swing.JTextField totalUSFacturaContado1;
    // End of variables declaration//GEN-END:variables
}
