/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author SHIDO-NYU
 */
public class Cheque extends javax.swing.JPanel {

    /**
     * Creates new form Cheque
     */
    public Cheque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpanelEsquinasRedondas1 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas3 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblChequeOriginal = new javax.swing.JLabel();

        jpanelEsquinasRedondas1.setBackground(new java.awt.Color(255, 255, 255));

        jpanelEsquinasRedondas3.setForeground(new java.awt.Color(255, 255, 255));
        jpanelEsquinasRedondas3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHEQUE No.");
        jpanelEsquinasRedondas3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    CODIGO CUENTA CLIENTE (CCC) ");
        jpanelEsquinasRedondas3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAGUESE POR ESTE CHEQUE A ");
        jpanelEsquinasRedondas3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 168, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LA SUMA DE ");
        jpanelEsquinasRedondas3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CORDOBAS");
        jpanelEsquinasRedondas3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SERIE N°");
        jpanelEsquinasRedondas3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha");
        jpanelEsquinasRedondas3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 90, 50, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Firma");
        jpanelEsquinasRedondas3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 280, 50, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconosderedessociales.png"))); // NOI18N
        jpanelEsquinasRedondas3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoCheque.png"))); // NOI18N
        jpanelEsquinasRedondas3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 200, 130));

        lblChequeOriginal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChequeOriginal.png"))); // NOI18N
        jpanelEsquinasRedondas3.add(lblChequeOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 360));

        javax.swing.GroupLayout jpanelEsquinasRedondas1Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas1);
        jpanelEsquinasRedondas1.setLayout(jpanelEsquinasRedondas1Layout);
        jpanelEsquinasRedondas1Layout.setHorizontalGroup(
            jpanelEsquinasRedondas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jpanelEsquinasRedondas3, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(311, 311, 311))
        );
        jpanelEsquinasRedondas1Layout.setVerticalGroup(
            jpanelEsquinasRedondas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jpanelEsquinasRedondas3, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jScrollPane1.setViewportView(jpanelEsquinasRedondas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas1;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas3;
    private javax.swing.JLabel lblChequeOriginal;
    // End of variables declaration//GEN-END:variables
}
