/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Lenovo
 */
public class DetalleChequeFlotante extends javax.swing.JPanel {

    /**
     * Creates new form ChequeFlotante
     */
    public DetalleChequeFlotante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpanelEsquinasRedondas1 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas8 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas11 = new Estilos_panel.jpanelEsquinasRedondas();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDetalleChequeFlotante = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        totalDetalleChequeFlotante = new javax.swing.JTextField();
        jpanelEsquinasRedondas10 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel2 = new javax.swing.JLabel();
        jpanelEsquinasRedondas9 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        jpanelEsquinasRedondas1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelEsquinasRedondas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelEsquinasRedondas8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetalleChequeFlotante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableDetalleChequeFlotante);

        javax.swing.GroupLayout jpanelEsquinasRedondas11Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas11);
        jpanelEsquinasRedondas11.setLayout(jpanelEsquinasRedondas11Layout);
        jpanelEsquinasRedondas11Layout.setHorizontalGroup(
            jpanelEsquinasRedondas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jpanelEsquinasRedondas11Layout.setVerticalGroup(
            jpanelEsquinasRedondas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas11Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jpanelEsquinasRedondas11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Total");
        jpanelEsquinasRedondas8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 331, 40, -1));

        totalDetalleChequeFlotante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        totalDetalleChequeFlotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDetalleChequeFlotanteActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas8.add(totalDetalleChequeFlotante, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 361, 100, 30));

        jpanelEsquinasRedondas10.setBackground(new java.awt.Color(153, 153, 255));
        jpanelEsquinasRedondas10.setPreferredSize(new java.awt.Dimension(1018, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DETALLE DE CHEQUE FLOTANTE");

        javax.swing.GroupLayout jpanelEsquinasRedondas10Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas10);
        jpanelEsquinasRedondas10.setLayout(jpanelEsquinasRedondas10Layout);
        jpanelEsquinasRedondas10Layout.setHorizontalGroup(
            jpanelEsquinasRedondas10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas10Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelEsquinasRedondas10Layout.setVerticalGroup(
            jpanelEsquinasRedondas10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEsquinasRedondas10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanelEsquinasRedondas8.add(jpanelEsquinasRedondas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 638, -1));

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 403));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Managua, Nicaragua");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel11.setText("Empresa Team 8");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Telefono No. 88888-76753");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setText("Foto");

        javax.swing.GroupLayout jpanelEsquinasRedondas9Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas9);
        jpanelEsquinasRedondas9.setLayout(jpanelEsquinasRedondas9Layout);
        jpanelEsquinasRedondas9Layout.setHorizontalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addGroup(jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12)))
                    .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel13)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelEsquinasRedondas9Layout.setVerticalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jpanelEsquinasRedondas1.add(jpanelEsquinasRedondas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 6, -1, -1));

        guardar.setBackground(new java.awt.Color(204, 204, 255));
        guardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorder(null);
        guardar.setBorderPainted(false);
        guardar.setFocusPainted(false);
        guardar.setFocusable(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 196, 90, 30));

        jScrollPane1.setViewportView(jpanelEsquinasRedondas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalDetalleChequeFlotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDetalleChequeFlotanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDetalleChequeFlotanteActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas1;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas10;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas11;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas8;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas9;
    private javax.swing.JTable tableDetalleChequeFlotante;
    public javax.swing.JTextField totalDetalleChequeFlotante;
    // End of variables declaration//GEN-END:variables
}
