/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Lenovo
 */
public class FacturaContado extends javax.swing.JPanel {

    /**
     * Creates new form FacturaContado
     */
    public FacturaContado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jpanelEsquinasRedondas6 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas8 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas9 = new Estilos_panel.jpanelEsquinasRedondas();
        jpanelEsquinasRedondas10 = new Estilos_panel.jpanelEsquinasRedondas();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clienteFacturaContado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        direccionFacturaContado = new javax.swing.JTextField();
        NoFacturaContado = new javax.swing.JTextField();
        jpanelEsquinasRedondas11 = new Estilos_panel.jpanelEsquinasRedondas();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFacturaContado = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        firmaFacturaContado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        totalFacturaContado = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jpanelEsquinasRedondas6.setBackground(new java.awt.Color(255, 255, 255));

        jpanelEsquinasRedondas8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelEsquinasRedondas9.setBackground(new java.awt.Color(217, 217, 246));

        jpanelEsquinasRedondas10.setBackground(new java.awt.Color(153, 153, 255));
        jpanelEsquinasRedondas10.setPreferredSize(new java.awt.Dimension(1018, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FACTURA AL CONTADO");

        javax.swing.GroupLayout jpanelEsquinasRedondas10Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas10);
        jpanelEsquinasRedondas10.setLayout(jpanelEsquinasRedondas10Layout);
        jpanelEsquinasRedondas10Layout.setHorizontalGroup(
            jpanelEsquinasRedondas10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas10Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelEsquinasRedondas10Layout.setVerticalGroup(
            jpanelEsquinasRedondas10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEsquinasRedondas10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fecha");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("No.");

        javax.swing.GroupLayout jpanelEsquinasRedondas9Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas9);
        jpanelEsquinasRedondas9.setLayout(jpanelEsquinasRedondas9Layout);
        jpanelEsquinasRedondas9Layout.setHorizontalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelEsquinasRedondas10, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jpanelEsquinasRedondas9Layout.setVerticalGroup(
            jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas9Layout.createSequentialGroup()
                .addComponent(jpanelEsquinasRedondas10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelEsquinasRedondas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jpanelEsquinasRedondas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        clienteFacturaContado.setForeground(new java.awt.Color(204, 204, 204));
        clienteFacturaContado.setBorder(null);
        jpanelEsquinasRedondas8.add(clienteFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 191, 30));

        jPanel4.setBackground(new java.awt.Color(217, 217, 246));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cliente (a)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, -1, -1));

        jPanel5.setBackground(new java.awt.Color(217, 217, 246));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Direccion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, -1, -1));

        direccionFacturaContado.setForeground(new java.awt.Color(204, 204, 204));
        direccionFacturaContado.setBorder(null);
        jpanelEsquinasRedondas8.add(direccionFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, 191, 30));

        NoFacturaContado.setForeground(new java.awt.Color(204, 204, 204));
        NoFacturaContado.setBorder(null);
        jpanelEsquinasRedondas8.add(NoFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 191, 30));

        tableFacturaContado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableFacturaContado);

        javax.swing.GroupLayout jpanelEsquinasRedondas11Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas11);
        jpanelEsquinasRedondas11.setLayout(jpanelEsquinasRedondas11Layout);
        jpanelEsquinasRedondas11Layout.setHorizontalGroup(
            jpanelEsquinasRedondas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        jpanelEsquinasRedondas11Layout.setVerticalGroup(
            jpanelEsquinasRedondas11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas11Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jpanelEsquinasRedondas11, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 114, -1, -1));

        jPanel6.setBackground(new java.awt.Color(217, 217, 246));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Firma");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jpanelEsquinasRedondas8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, -1, -1));

        firmaFacturaContado.setForeground(new java.awt.Color(204, 204, 204));
        firmaFacturaContado.setBorder(null);
        firmaFacturaContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firmaFacturaContadoActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas8.add(firmaFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 294, 191, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Total");
        jpanelEsquinasRedondas8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 331, 40, -1));

        totalFacturaContado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        totalFacturaContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFacturaContadoActionPerformed(evt);
            }
        });
        jpanelEsquinasRedondas8.add(totalFacturaContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 361, 100, 30));

        javax.swing.GroupLayout jpanelEsquinasRedondas6Layout = new javax.swing.GroupLayout(jpanelEsquinasRedondas6);
        jpanelEsquinasRedondas6.setLayout(jpanelEsquinasRedondas6Layout);
        jpanelEsquinasRedondas6Layout.setHorizontalGroup(
            jpanelEsquinasRedondas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jpanelEsquinasRedondas8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(789, Short.MAX_VALUE))
        );
        jpanelEsquinasRedondas6Layout.setVerticalGroup(
            jpanelEsquinasRedondas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEsquinasRedondas6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelEsquinasRedondas8, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jScrollPane2.setViewportView(jpanelEsquinasRedondas6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalFacturaContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFacturaContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFacturaContadoActionPerformed

    private void firmaFacturaContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firmaFacturaContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firmaFacturaContadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField NoFacturaContado;
    public javax.swing.JTextField clienteFacturaContado;
    public javax.swing.JTextField direccionFacturaContado;
    public javax.swing.JTextField firmaFacturaContado;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas10;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas11;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas6;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas8;
    private Estilos_panel.jpanelEsquinasRedondas jpanelEsquinasRedondas9;
    private javax.swing.JTable tableFacturaContado;
    public javax.swing.JTextField totalFacturaContado;
    // End of variables declaration//GEN-END:variables
}
